### ISSUE TITLE
Add prepush validation 

### ISSUE THREAD

**Issue by kevinv11n** [trailheadapps/ebikes-lwc#18]
Enforcement at prepush is less intrusive than precommit: you can make many local changes without interruption, then adhere to project requirements when you share your branch. It removes friction in throw-away branches that you never plan on sharing. 

We should use a prepush hook to verify:
- linting passes
- prettier passes (eg no changes are generated)
- unit tests pass

We should evaluate the precommit hook: it lints LWC and Aura. Do we need that on each commit or is catching it at push time sufficient?

**Comment by muenzpraeger** [comment]
I think it's debatable:

- Prettier and linting - before commit
- Unit tests on CI level (instead of pre-push/commit)

As @trevor-bliss mentioned it's good to move the unit tests to CI, as they will/take some time, depending on the project size.

On Prettier and Lint I want to be more prescriptive. Fix before commit.
