### ISSUE TITLE
error while running command

### ISSUE THREAD

**Issue by sigamala2** [trailheadapps/ebikes-lwc#338]
### Summary

_Short summary of what is going on or to provide context_.

### Steps To Reproduce:

1.  We couldn't validate componentAttributes in E_Bikes1/themes/jepson.json for component 1dccf062-078a-4fde-a185-1c6b822db8b0. Error: attribute [navigationMenuEditorRefresh]: The navigation menu Default_Navigation doesn’t exist.. Check your file and try again.
1.  sfdx force:source:deploy -p force-app when i ran this command on VSCode i am getting above issue

### Expected result

_Describe what should have happened_.

### Actual result

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot or code snippets_.

**Comment by prasanthk857** [comment]
Hey there , Is there any fix to this error yet?
Steps To Reproduce:
We couldn't validate componentAttributes in E_Bikes1/themes/jepson.json for component 1dccf062-078a-4fde-a185-1c6b822db8b0. Error: attribute [navigationMenuEditorRefresh]: The navigation menu Default_Navigation doesn’t exist.. Check your file and try again.

**Comment by Jacjs27** [comment]
Hi,
Is there an answer for this?

**Comment by pozil** [comment]
Hi @Jacjs27 this kind of error is likely happening due to a metadata breaking change introduced in the upcoming release (Winter '24 at time of writing).

The metadata from the `main` branch of this repo is only compatible with the current Salesforce release (Summer '23 as of now) and not yet compatible with pre-release orgs. We will update this repo's metadata when the Salesforce release is out.
